import { Router } from 'express';
import { PERMISSIONS } from '../../shared/constants/roles.js';
import { authenticate } from '../../shared/middleware/authenticate.js';
import { authorize } from '../../shared/middleware/authorize.js';
import { validate } from '../../shared/middleware/validate.js';
import { asyncHandler } from '../../shared/utils/async-handler.js';
import * as controller from './operations.controller.js';
import { auditQuerySchema,listingReviewSchema,submitListingSchema,userGovernanceSchema } from './operations.schemas.js';
const router=Router();router.use(authenticate);
router.post('/properties/:id/submit',authorize(PERMISSIONS.PROPERTY_EDIT_OWN),validate(submitListingSchema),asyncHandler(controller.submitListing));
router.get('/moderation/listings',authorize(PERMISSIONS.MODERATION_REVIEW),asyncHandler(controller.reviewQueue));router.patch('/moderation/listings/:id',authorize(PERMISSIONS.PROPERTY_VERIFY),validate(listingReviewSchema),asyncHandler(controller.reviewListing));
router.get('/admin/users',authorize(PERMISSIONS.USER_MANAGE),asyncHandler(controller.users));router.patch('/admin/users/:id',authorize(PERMISSIONS.USER_MANAGE),validate(userGovernanceSchema),asyncHandler(controller.governUser));
router.get('/admin/analytics',authorize(PERMISSIONS.ANALYTICS_VIEW_ALL),asyncHandler(controller.analytics));router.get('/admin/audit-logs',authorize(PERMISSIONS.AUDIT_VIEW),validate(auditQuerySchema),asyncHandler(controller.audits));
export default router;
