import { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { apiClient } from '@services/apiClient.js';
const money=(value)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(value);
export function ExplorePage(){
  const[params,setParams]=useSearchParams();const[properties,setProperties]=useState([]);const[meta,setMeta]=useState(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
  useEffect(()=>{let active=true;setLoading(true);apiClient(`/properties?${params.toString()}`).then(payload=>{if(active){setProperties(payload.data);setMeta(payload.meta);setError('');}}).catch(requestError=>active&&setError(requestError.message)).finally(()=>active&&setLoading(false));return()=>{active=false;};},[params]);
  const submit=(event)=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));setParams(Object.fromEntries(Object.entries(values).filter(([,value])=>value)));};
  return <main className="content-page explore-page"><p className="section-kicker"><span>Explore</span> Verified homes & projects</p><h1>Find space for what comes next.</h1><form className="explore-filters" onSubmit={submit}><label>Search<input name="q" defaultValue={params.get('q')||''} placeholder="City, locality or residence" /></label><label>Purpose<select name="listingType" defaultValue={params.get('listingType')||''}><option value="">Buy or rent</option><option value="buy">Buy</option><option value="rent">Rent</option></select></label><label>Maximum price<input name="maxPrice" type="number" min="0" defaultValue={params.get('maxPrice')||''} placeholder="₹" /></label><button>Search</button></form>{loading&&<p className="workspace-empty">Finding verified residences…</p>}{error&&<p className="workspace-error">{error}</p>}{!loading&&!error&&<><p className="explore-count">{meta?.total||properties.length} residences · {meta?.source==='DEMO_SEED'?'curated preview':'live marketplace'}</p><div className="property-list">{properties.map((property)=><Link className="property-card" key={property._id||property.id} to={`/properties/${property.slug}`}><div className="visual" style={{backgroundImage:`url(${property.coverImage||property.media?.find(item=>item.isCover)?.url||'/media/properties/modern-villa.png'})`}}/><h2>{property.title}</h2><p>{property.locality}, {property.city}<br/>{property.bedrooms??'—'} BHK · {property.carpetArea?.toLocaleString('en-IN')||'—'} sq.ft. · {money(property.price)}</p></Link>)}</div></>}</main>;
}
