import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useAuth } from '../auth/AuthContext.jsx';
import { apiClient } from '@services/apiClient.js';
import { ROUTES } from '@config/routes.js';
const money=(value)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(value);
export function PropertyPage(){
  const{slug}=useParams();const{user}=useAuth();const[property,setProperty]=useState(null);const[error,setError]=useState('');const[notice,setNotice]=useState('');const[busy,setBusy]=useState(false);
  useEffect(()=>{apiClient(`/properties/${slug}`).then(payload=>setProperty(payload.data)).catch(requestError=>setError(requestError.message));},[slug]);
  async function act(event,type){event.preventDefault();if(!property?._id){setNotice('This is a curated preview. Live actions become available on marketplace listings.');return;}setBusy(true);setNotice('');const values=Object.fromEntries(new FormData(event.currentTarget));try{let endpoint,body;if(type==='booking'){endpoint='/bookings';body={propertyId:property._id,scheduledFor:new Date(values.scheduledFor).toISOString(),mode:values.mode,note:values.note};}if(type==='message'){endpoint='/conversations';body={propertyId:property._id,body:values.body};}if(type==='offer'){endpoint='/offers';body={propertyId:property._id,amount:Number(values.amount),currency:'INR',expiresAt:new Date(values.expiresAt).toISOString(),conditions:values.conditions?[values.conditions]:[]};}const response=await apiClient(endpoint,{method:'POST',body:JSON.stringify(body)});setNotice(response.message);}catch(requestError){setNotice(requestError.message);}finally{setBusy(false);}}
  if(error)return <main className="content-page"><p className="workspace-error">{error}</p></main>;if(!property)return <main className="content-page"><p className="workspace-empty">Preparing property intelligence…</p></main>;
  const image=property.coverImage||property.media?.find(item=>item.isCover)?.url||'/media/properties/modern-villa.png';
  return <main className="property-detail"><section className="property-detail-hero" style={{backgroundImage:`linear-gradient(180deg,transparent,rgb(5 9 6 / 78%)),url(${image})`}}><div><p className="section-kicker"><span>{property.verified?'Verified residence':'Curated residence'}</span> {property.city}</p><h1>{property.title}</h1><p>{property.bedrooms??'—'} BHK · {property.carpetArea?.toLocaleString('en-IN')||'—'} sq.ft. · {money(property.price)}</p></div></section><section className="property-detail-grid"><article><p className="section-kicker"><span>Overview</span> {property.locality}</p><h2>Designed around considered living.</h2><p>{property.description||'A premium residence with verified context, thoughtful spatial planning and connected transaction workflows.'}</p><dl><div><dt>Purpose</dt><dd>{property.listingType}</dd></div><div><dt>Type</dt><dd>{property.propertyType}</dd></div><div><dt>Bathrooms</dt><dd>{property.bathrooms??'—'}</dd></div><div><dt>Status</dt><dd>{property.status}</dd></div></dl></article><aside className="property-actions">{!user?<div className="action-login"><h3>Begin your journey</h3><p>Sign in to book a visit, message the owner or make an offer.</p><Link to={ROUTES.LOGIN}>Secure sign in →</Link></div>:<><form onSubmit={event=>act(event,'booking')}><h3>Schedule a visit</h3><input name="scheduledFor" type="datetime-local" required/><select name="mode"><option value="IN_PERSON">In person</option><option value="VIDEO">Video tour</option></select><input name="note" placeholder="A note for the host"/><button disabled={busy}>Request visit</button></form><form onSubmit={event=>act(event,'message')}><h3>Message the owner</h3><textarea name="body" minLength="1" maxLength="4000" required placeholder="Ask about the residence…"/><button disabled={busy}>Send securely</button></form>{property.listingType==='buy'&&<form onSubmit={event=>act(event,'offer')}><h3>Make an offer</h3><input name="amount" type="number" min="1" required placeholder="Offer amount in ₹"/><input name="expiresAt" type="datetime-local" required/><input name="conditions" placeholder="Optional conditions"/><button disabled={busy}>Submit offer</button></form>}</>}{notice&&<p className="action-notice" role="status">{notice}</p>}</aside></section></main>;
}
