export const ROUTES = Object.freeze({
  HOME: '/',
  EXPLORE: '/explore',
  PROPERTY: '/properties/:slug',
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  BOOKINGS: '/dashboard/bookings',
  MESSAGES: '/dashboard/messages',
  OFFERS: '/dashboard/offers',
  DOCUMENTS: '/dashboard/documents',
  NOTIFICATIONS: '/dashboard/notifications',
  ADMIN: '/dashboard/admin',
  PROJECTS: '/dashboard/projects',
  LEADS: '/dashboard/leads',
  LEASES: '/dashboard/leases',
  MAINTENANCE: '/dashboard/maintenance',
  LISTINGS: '/dashboard/listings',
  MODERATION: '/dashboard/moderation',
  USERS: '/dashboard/users',
});
