export const USER_ROLES = Object.freeze({
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  MODERATOR: 'MODERATOR',
  BUILDER: 'BUILDER',
  AGENT: 'AGENT',
  PROPERTY_MANAGER: 'PROPERTY_MANAGER',
  SELLER: 'SELLER',
  BUYER: 'BUYER',
});

export const PERMISSIONS = Object.freeze({
  PROPERTY_CREATE: 'PROPERTY_CREATE', PROPERTY_EDIT_OWN: 'PROPERTY_EDIT_OWN', PROPERTY_EDIT_ANY: 'PROPERTY_EDIT_ANY',
  PROPERTY_VERIFY: 'PROPERTY_VERIFY', PROPERTY_DELETE: 'PROPERTY_DELETE', USER_MANAGE: 'USER_MANAGE',
  ROLE_MANAGE: 'ROLE_MANAGE', MODERATION_REVIEW: 'MODERATION_REVIEW', DOCUMENT_VERIFY: 'DOCUMENT_VERIFY',
  BOOKING_MANAGE_OWN: 'BOOKING_MANAGE_OWN', BOOKING_MANAGE_ANY: 'BOOKING_MANAGE_ANY', CHAT_USE: 'CHAT_USE',
  OFFER_CREATE: 'OFFER_CREATE', OFFER_REVIEW: 'OFFER_REVIEW', ANALYTICS_VIEW_OWN: 'ANALYTICS_VIEW_OWN',
  ANALYTICS_VIEW_ALL: 'ANALYTICS_VIEW_ALL', AUDIT_VIEW: 'AUDIT_VIEW', INVENTORY_MANAGE: 'INVENTORY_MANAGE',
  RENTAL_MANAGE: 'RENTAL_MANAGE', LEAD_MANAGE: 'LEAD_MANAGE',
});

const common = [PERMISSIONS.BOOKING_MANAGE_OWN, PERMISSIONS.CHAT_USE, PERMISSIONS.ANALYTICS_VIEW_OWN];
export const ROLE_PERMISSIONS = Object.freeze({
  [USER_ROLES.BUYER]: [...common, PERMISSIONS.OFFER_CREATE],
  [USER_ROLES.SELLER]: [...common, PERMISSIONS.PROPERTY_CREATE, PERMISSIONS.PROPERTY_EDIT_OWN, PERMISSIONS.OFFER_REVIEW],
  [USER_ROLES.AGENT]: [...common, PERMISSIONS.PROPERTY_CREATE, PERMISSIONS.PROPERTY_EDIT_OWN, PERMISSIONS.OFFER_REVIEW, PERMISSIONS.LEAD_MANAGE],
  [USER_ROLES.BUILDER]: [...common, PERMISSIONS.PROPERTY_CREATE, PERMISSIONS.PROPERTY_EDIT_OWN, PERMISSIONS.INVENTORY_MANAGE, PERMISSIONS.LEAD_MANAGE],
  [USER_ROLES.PROPERTY_MANAGER]: [...common, PERMISSIONS.RENTAL_MANAGE],
  [USER_ROLES.MODERATOR]: [PERMISSIONS.PROPERTY_VERIFY, PERMISSIONS.MODERATION_REVIEW, PERMISSIONS.DOCUMENT_VERIFY, PERMISSIONS.AUDIT_VIEW],
  [USER_ROLES.ADMIN]: Object.values(PERMISSIONS).filter((permission) => permission !== PERMISSIONS.ROLE_MANAGE),
  [USER_ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
});
