import { useState } from 'react';
import { useAuth } from '../../auth/AuthContext.jsx';
import { apiClient } from '@services/apiClient.js';

const idOf=(value)=>typeof value==='string'?value:value?._id||value?.id;
export function ModuleItemActions({moduleKey,item,onChanged}){
  const{user}=useAuth();const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');
  async function mutate(endpoint,method='PATCH',body){setBusy(true);setMessage('');try{const response=await apiClient(endpoint,{method,...(body?{body:JSON.stringify(body)}:{})});setMessage(response.message);onChanged();}catch(error){setMessage(error.message);}finally{setBusy(false);}}
  async function submitForm(event,handler){event.preventDefault();const form=event.currentTarget;await handler(Object.fromEntries(new FormData(form)),form);}
  let controls=null;
  if(moduleKey==='listings')controls=<div>{['DRAFT','CHANGES_REQUESTED'].includes(item.status)&&<><form onSubmit={event=>submitForm(event,values=>mutate(`/properties/${item._id}`,'PATCH',{title:values.title,description:values.description,price:Number(values.price)}))}><input name="title" defaultValue={item.title} minLength="5" maxLength="160" required/><textarea name="description" defaultValue={item.description} minLength="30" maxLength="5000" required/><input name="price" type="number" min="0" defaultValue={item.price} required/><button disabled={busy}>Save draft</button></form><button onClick={()=>mutate(`/properties/${item._id}/submit`,'POST')} disabled={busy}>Submit for review</button></>}<form onSubmit={event=>submitForm(event,values=>mutate(`/properties/${item._id}/managers`,'PATCH',{...values,action:'ASSIGN'}))}><input name="userId" required placeholder="Property manager user ID"/><button disabled={busy}>Assign manager</button></form></div>;
  if(moduleKey==='moderation')controls=<form onSubmit={event=>submitForm(event,values=>mutate(`/moderation/listings/${item._id}`,'PATCH',values))}><select name="status"><option value="PUBLISHED">Publish</option><option value="CHANGES_REQUESTED">Request changes</option><option value="REJECTED">Reject</option><option value="SUSPENDED">Suspend</option></select><input name="reason" minLength="3" required placeholder="Review reason"/><button disabled={busy}>Apply review</button></form>;
  if(moduleKey==='bookings'){const host=idOf(item.hostId)===user.id;const options=host?['CONFIRMED','RESCHEDULED','COMPLETED','CANCELLED','NO_SHOW']:['RESCHEDULED','CANCELLED'];if(!['COMPLETED','CANCELLED','NO_SHOW'].includes(item.status))controls=<form onSubmit={event=>submitForm(event,values=>mutate(`/bookings/${item._id}`,'PATCH',{...values,...(values.scheduledFor?{scheduledFor:new Date(values.scheduledFor).toISOString()}:{})}))}><select name="status">{options.map(value=><option key={value}>{value}</option>)}</select><input name="scheduledFor" type="datetime-local"/><input name="reason" placeholder="Optional note"/><button disabled={busy}>Update visit</button></form>;}
  if(moduleKey==='messages')controls=<form onSubmit={event=>submitForm(event,async(values,form)=>{await mutate(`/conversations/${item._id}/messages`,'POST',values);form.reset();})}><input name="body" required maxLength="4000" placeholder="Write a reply"/><button disabled={busy}>Send</button></form>;
  if(moduleKey==='offers'){const buyer=idOf(item.buyerId)===user.id,seller=idOf(item.sellerId)===user.id;if(['PENDING','COUNTERED'].includes(item.status))controls=<div>{seller&&item.status==='PENDING'&&<><button onClick={()=>mutate(`/offers/${item._id}`,'PATCH',{action:'ACCEPT'})}>Accept</button><form onSubmit={event=>submitForm(event,values=>mutate(`/offers/${item._id}`,'PATCH',{action:'COUNTER',amount:Number(values.amount),expiresAt:new Date(values.expiresAt).toISOString()}))}><input name="amount" type="number" min="1" required placeholder="Counter amount"/><input name="expiresAt" type="datetime-local" required/><button>Counter</button></form></>}{buyer&&item.status==='COUNTERED'&&<button onClick={()=>mutate(`/offers/${item._id}`,'PATCH',{action:'ACCEPT'})}>Accept counter</button>}<button onClick={()=>mutate(`/offers/${item._id}`,'PATCH',{action:buyer?'WITHDRAW':'REJECT'})}>{buyer?'Withdraw':'Reject'}</button></div>;}
  if(moduleKey==='documents'&&['MODERATOR','ADMIN','SUPER_ADMIN'].includes(user.role))controls=<form onSubmit={event=>submitForm(event,values=>mutate(`/documents/${item._id}/review`,'PATCH',values))}><select name="status"><option value="VERIFIED">Verify</option><option value="UNDER_REVIEW">Under review</option><option value="REJECTED">Reject</option></select><input name="note" placeholder="Verification note"/><button disabled={busy}>Review</button></form>;
  if(moduleKey==='documents'){const review=controls;controls=<div><button type="button" onClick={async()=>{setBusy(true);setMessage('');try{const blob=await apiClient(`/documents/${item._id}/download`,{responseType:'blob'});const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=item.name;anchor.click();URL.revokeObjectURL(url);}catch(error){setMessage(error.message);}finally{setBusy(false);}}} disabled={busy}>Download</button>{review}</div>;}
  if(moduleKey==='notifications'&&!item.readAt)controls=<button onClick={()=>mutate(`/notifications/${item._id}/read`)} disabled={busy}>Mark read</button>;
  if(moduleKey==='leads')controls=<form onSubmit={event=>submitForm(event,values=>mutate(`/leads/${item._id}`,'PATCH',{...values,score:values.score?Number(values.score):undefined}))}><select name="stage" defaultValue={item.stage}>{['NEW','CONTACTED','QUALIFIED','VISIT','NEGOTIATION','WON','LOST'].map(value=><option key={value}>{value}</option>)}</select><input name="score" type="number" min="0" max="100" defaultValue={item.score}/><input name="note" placeholder="Pipeline note"/><button disabled={busy}>Update</button></form>;
  if(moduleKey==='projects')controls=<form onSubmit={event=>submitForm(event,values=>mutate(`/projects/${item._id}/units`,'POST',{...values,floor:values.floor?Number(values.floor):undefined,bedrooms:values.bedrooms?Number(values.bedrooms):undefined,area:values.area?Number(values.area):undefined,price:values.price?Number(values.price):undefined}))}><input name="unitNumber" required maxLength="30" placeholder="Unit number"/><input name="type" required maxLength="60" placeholder="Unit type"/><input name="tower" maxLength="50" placeholder="Tower"/><input name="floor" type="number" placeholder="Floor"/><input name="bedrooms" type="number" min="0" placeholder="Bedrooms"/><input name="area" type="number" min="1" placeholder="Area"/><input name="price" type="number" min="0" placeholder="Price"/><button disabled={busy}>Add inventory unit</button></form>;
  if(moduleKey==='leases'){const transitions={DRAFT:['ACTIVE','TERMINATED'],ACTIVE:['NOTICE','EXPIRED','TERMINATED'],NOTICE:['ACTIVE','EXPIRED','TERMINATED']}[item.status]||[];if(transitions.length)controls=<form onSubmit={event=>submitForm(event,values=>mutate(`/leases/${item._id}`,'PATCH',values))}><select name="status">{transitions.map(value=><option key={value}>{value}</option>)}</select><input name="note" maxLength="1000" placeholder="Status note"/><button disabled={busy}>Update lease</button></form>;}
  if(moduleKey==='maintenance')controls=<form onSubmit={event=>submitForm(event,values=>mutate(`/maintenance/${item._id}`,'PATCH',values))}><select name="status" defaultValue={item.status}>{['OPEN','ASSIGNED','IN_PROGRESS','RESOLVED','CLOSED'].map(value=><option key={value}>{value}</option>)}</select><select name="priority" defaultValue={item.priority}>{['LOW','MEDIUM','HIGH','URGENT'].map(value=><option key={value}>{value}</option>)}</select><button disabled={busy}>Update ticket</button></form>;
  if(moduleKey==='users'&&item.id!==user.id&&item._id!==user.id)controls=<form onSubmit={event=>submitForm(event,values=>mutate(`/admin/users/${item._id}`,'PATCH',values))}><select name="status" defaultValue={item.status}>{['ACTIVE','LOCKED','SUSPENDED','DELETED'].map(value=><option key={value}>{value}</option>)}</select>{user.role==='SUPER_ADMIN'&&<select name="role" defaultValue={item.role}>{['BUYER','SELLER','AGENT','BUILDER','PROPERTY_MANAGER','MODERATOR','ADMIN','SUPER_ADMIN'].map(value=><option key={value}>{value}</option>)}</select>}<button disabled={busy}>Save user</button></form>;
  if(!controls)return null;return <div className="workspace-actions">{controls}{message&&<small role="status">{message}</small>}</div>;
}
