import { useState } from 'react';
import { apiClient } from '@services/apiClient.js';
import { useAuth } from '../../auth/AuthContext.jsx';

const CONFIG={
  listings:{roles:['SELLER','AGENT','BUILDER','ADMIN','SUPER_ADMIN'],endpoint:'/properties',button:'Create draft listing',fields:[['title','Property title'],['description','Detailed description','textarea'],['listingType','Purpose','select',['buy','rent']],['propertyType','Property type'],['price','Price','number'],['bedrooms','Bedrooms','number'],['bathrooms','Bathrooms','number'],['carpetArea','Carpet area','number'],['city','City'],['locality','Locality'],['state','State'],['postalCode','Postal code']]},
  projects:{roles:['BUILDER','ADMIN','SUPER_ADMIN'],endpoint:'/projects',button:'Create project',fields:[['name','Project name'],['city','City'],['locality','Locality'],['description','Description','textarea'],['status','Stage','select',['PLANNING','PRE_LAUNCH','UNDER_CONSTRUCTION','READY','COMPLETED']]]},
  leads:{roles:['AGENT','BUILDER','ADMIN','SUPER_ADMIN'],endpoint:'/leads',button:'Add lead',fields:[['name','Lead name'],['email','Email','email'],['phone','Phone'],['source','Source','select',['INQUIRY','REFERRAL','CAMPAIGN','WALK_IN','OTHER']],['budget','Budget','number'],['score','Lead score','number'],['nextFollowUpAt','Next follow-up','datetime-local']]},
  leases:{roles:['PROPERTY_MANAGER','ADMIN','SUPER_ADMIN'],endpoint:'/leases',button:'Create lease',fields:[['propertyId','Property ID'],['tenantId','Tenant user ID'],['startDate','Start date','date'],['endDate','End date','date'],['monthlyRent','Monthly rent','number'],['deposit','Deposit','number'],['paymentDay','Payment day','number']]},
  maintenance:{roles:['PROPERTY_MANAGER','ADMIN','SUPER_ADMIN'],endpoint:'/maintenance',button:'Create ticket',fields:[['propertyId','Property ID'],['tenantId','Tenant user ID'],['title','Issue title'],['description','Description','textarea'],['priority','Priority','select',['LOW','MEDIUM','HIGH','URGENT']]]},
  documents:{roles:['SELLER','AGENT','BUILDER','PROPERTY_MANAGER','ADMIN','SUPER_ADMIN'],endpoint:'/documents',button:'Upload document',multipart:true,fields:[['propertyId','Property ID'],['category','Category','select',['OWNERSHIP','IDENTITY','APPROVAL','AGREEMENT','FLOOR_PLAN','OTHER']],['visibility','Visibility','select',['PRIVATE','TRANSACTION_PARTIES','PUBLIC']],['file','PDF or property image','file']]},
};
const numeric=new Set(['price','bedrooms','bathrooms','carpetArea','budget','score','monthlyRent','deposit','paymentDay']);
const dates=new Set(['nextFollowUpAt','startDate','endDate']);
export function ModuleCreateForm({moduleKey,onCreated}){
  const{user}=useAuth();const config=CONFIG[moduleKey];const[open,setOpen]=useState(false);const[busy,setBusy]=useState(false);const[message,setMessage]=useState('');if(!config||!config.roles.includes(user.role))return null;
  async function submit(event){event.preventDefault();setBusy(true);setMessage('');const formData=new FormData(event.currentTarget);const raw=Object.fromEntries(formData);const body=Object.fromEntries(Object.entries(raw).filter(([,value])=>value!=='').map(([key,value])=>[key,numeric.has(key)?Number(value):dates.has(key)?new Date(value).toISOString():value]));try{const response=await apiClient(config.endpoint,{method:'POST',body:config.multipart?formData:JSON.stringify(body)});setMessage(response.message);event.currentTarget.reset();onCreated();}catch(error){setMessage(error.message);}finally{setBusy(false);}}
  return <section className="workspace-create"><button type="button" onClick={()=>setOpen(value=>!value)}>{open?'Close form':config.button} <span>{open?'×':'+'}</span></button>{open&&<form onSubmit={submit}><h2>{config.button}</h2><div>{config.fields.map(([name,label,type='text',options])=><label key={name}>{label}{type==='textarea'?<textarea name={name} required={['description'].includes(name)}/>:type==='select'?<select name={name}>{options.map(option=><option key={option} value={option}>{option.replaceAll('_',' ')}</option>)}</select>:<input name={name} type={type} accept={type==='file'?'.pdf,.jpg,.jpeg,.png,.webp':undefined} required={!['postalCode','email','phone','budget','score','nextFollowUpAt','tenantId','deposit','bedrooms','bathrooms','carpetArea'].includes(name)} min={type==='number'?'0':undefined}/>}</label>)}</div><button disabled={busy}>{busy?'Saving…':config.button}</button>{message&&<p role="status">{message}</p>}</form>}</section>;
}
