import { Router } from 'express';
import { PERMISSIONS } from '../../shared/constants/roles.js';
import { authenticate } from '../../shared/middleware/authenticate.js';
import { authorize } from '../../shared/middleware/authorize.js';
import { validate } from '../../shared/middleware/validate.js';
import { asyncHandler } from '../../shared/utils/async-handler.js';
import * as controller from './property.controller.js';
import { createPropertySchema, inquirySchema, managerSchema, updatePropertySchema } from './property.schemas.js';
const router=Router();
router.get('/',asyncHandler(controller.listProperties));
router.get('/mine',authenticate,authorize(PERMISSIONS.PROPERTY_EDIT_OWN),asyncHandler(controller.mine));
router.get('/managed',authenticate,asyncHandler(controller.managed));
router.post('/',authenticate,authorize(PERMISSIONS.PROPERTY_CREATE),validate(createPropertySchema),asyncHandler(controller.createProperty));
router.patch('/:id',authenticate,authorize(PERMISSIONS.PROPERTY_EDIT_OWN),validate(updatePropertySchema),asyncHandler(controller.updateProperty));
router.patch('/:id/managers',authenticate,authorize(PERMISSIONS.PROPERTY_EDIT_OWN),validate(managerSchema),asyncHandler(controller.manager));
router.post('/:id/favourite',authenticate,asyncHandler(controller.favourite));
router.post('/:id/inquiries',authenticate,validate(inquirySchema),asyncHandler(controller.inquire));
router.get('/:slug',asyncHandler(controller.showProperty));
export default router;
